spring:
  application:
    name: Hello_Shoe_pvt_ltd
  datasource:
    url: jdbc:mysql://localhost:3306/hello_shoe_pvt_ltd?createDatabaseIfNotExist=true
    username: root
    password: dragon25
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8000
  servlet:
    context-path: /hello-shoe

